const config = {
  mongoURL: process.env.MONGO_URL || 'mongodb://localhost:27017/stage3-admin',
  port: process.env.PORT || 8000,
  access_token: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU3NDg5NDUsInVzZXJfbmFtZSI6ImJhY2tlbmRhZG1pbkBzdGFnZTMuY28iLCJhdXRob3JpdGllcyI6WyJST0xFX0FOT05ZTU9VUyIsIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwianRpIjoiMjczZjU3YmItOGQ2Ny00MDRlLWI3NDMtMDI4ZGE4N2I2MmMyIiwiY2xpZW50X2lkIjoiZWRnZSIsInNjb3BlIjpbInBhc3N3b3JkIl19.ELO4jXM8ydQzTyKT87MJBk5NwnKAulLqSfN-i2-LweY","token_type":"bearer","refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJiYWNrZW5kYWRtaW5Ac3RhZ2UzLmNvIiwic2NvcGUiOlsicGFzc3dvcmQiXSwiYXRpIjoiMjczZjU3YmItOGQ2Ny00MDRlLWI3NDMtMDI4ZGE4N2I2MmMyIiwiZXhwIjoxNjA2ODA0OTQ1LCJhdXRob3JpdGllcyI6WyJST0xFX0FOT05ZTU9VUyIsIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwianRpIjoiZjk4YTM2MzYtMzI5Yy00MTgyLWE4MzAtNmFhMjUzMzVjODhkIiwiY2xpZW50X2lkIjoiZWRnZSJ9.54OHH_PfaYyT1pSnaSFjPWCFnP3aWZUGmuqv6qQWm6c',
  targetURL: 'https://staging.stage3.co',
  notificationUrl: 'https://notification-test.stage3.co',
  refundKey: 'backendsecretstage123'
};

export default config;
